export const ENV = {
    SUPABASE_API_KEY: process.env.NEXT_PUBLIC_SUPABASE_API,
    SUPABASE_PROJECT_URL: process.env.NEXT_PUBLIC_SUPABASE_PROJECT,
    WEBSITE_DOMAIN: process.env.NEXT_PUBLIC_WEBSITE_DOMAIN,
};
