export const ENV = {
    SUPABASE_API_KEY: process.env.NEXT_PUBLIC_SUPABSE_API,
    SUPABASE_PROJECT_URL: process.env.NEXT_PUBLIC_SUPABSE_PROJECT,
    WEBSITE_DOMAIN: process.env.NEXT_PUBLIC_WEBSITE_DOMAIN,
};
